version: "3.3"
networks:
  celec-website-network:
services:
  meilisearch:
    container_name: meilisearch_celec_web
    image: getmeili/meilisearch:v0.25.2
    ports:
      - 7770:7700
    volumes:
      - ./meilisearch:/data.ms
    networks:
      - celec-website-network
    environment:
      MEILI_MASTER_KEY: YOUR_KEY
  npm-web:
    container_name: npm_celec_web
    image: node:latest
    working_dir: /var/www/html/web
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes: 
      - ./src/:/var/www/html/web
    networks:
      - celec-website-network
  mariadb:
    container_name: mariadb_celec_web
    image: mariadb:10.7
    ports: 
      - "3306:3306"
    networks:
      - celec-website-network
    volumes:
      - ./maria:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_database_password
      MYSQL_DATABASE: you_database_name
      MYSQL_USER: root
  php:
    build: ./php
    container_name: php_celec_web
    volumes:
      - ./src/:/var/www/html/
      - ./php/supervisor/conf.d:/etc/supervisor/conf.d
    networks:
      - celec-website-network
    command: bash -c "touch /var/run/supervisor.sock && supervisord -c /etc/supervisor/supervisord.conf"
  nginx:
    image: nginx:stable
    container_name: nginx_celec_web
    volumes:
      - ./src:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - celec-website-network
    ports:
      - "8085:80"
  redis:
    image: redis:6.2
    container_name: redis_celec_web
    image: 'bitnami/redis:latest'
    networks:
      - celec-website-network
